### PR TITLE
Fixes for tests to run under python 311

### PR DESCRIPTION
**Pull request by kokroo**
Ongoing fixes for tests under Python 3.11 are included in this PR.
I will add more commits until all tests are fixed.

### CODE REVIEW

**Comment by asgibson** [comment]
@kokroo, are you able to run the unit tests locally?

**Comment by kokroo** [comment]
> @kokroo, are you able to run the unit tests locally?

Yes, I'm using this command from the readme:
"python driver.py -t"

I hope I didn't do it wrong. I actually tried Python 3.9, 3.11.2 (like you did, to get ride of a few failed tests) and 3.11.4.

There's just one extra failed test on 3.11.4 which I've already fixed. I believe we should be running the testing in a 3.11.4 environment since I've already brought it to parity with the failed tests in 3.11.2

I did a really deep dive into why these errors are happening to begin with. Between Python 3.10 and Python 3.11 there were a lot of changes under the hood concerning how objects are stored and represented in memory and how methods and attributes paths are accessed.

Even after using a debugger I haven't been able to get rid of 2 tests that are still failing.

I suggest we should also update all the dependences to their latest versions, since the versions pinned in the requirements do not support Python 3.11, but the latest versions of the dependencies do support everything including 3.8, 3.9,3.10 and 3.11 and even support for 3.12.

**Comment by asgibson** [comment]
@kokroo, thank you for the assistance. We wouldn't have understood the problem as well without it. The code has superseded the original issues we were encountering (code and tests changed) and branch 14 was rebased with these changes. I am closing this PR because of those updates. An additional problem was found after the rebase but fixed and noted in #14 with new PR #57.

**Comment by kokroo** [comment]
@asgibson Thank you, good catch with the str and IDs there. I'm a bit confused now, are there any tests that are still failing after these fixes? If not, I'd even like to test 3.11.x versions as well as 3.12!

**Comment by asgibson** [comment]
@kokroo, 3.11.2 is now being used with the "unit test run" workflow and all tests are passing. I would definitely like to know what happens when running with 3.12. Thanks for your continued interest!

**Pull request closed without merging**
