### PR TITLE
[nasa/onair#9] Add CI Pipeline

### PR DESCRIPTION
**Pull request by jlucas9**
@asgibson did the heavy lifting here - I just pushed the first code coverage up and added fun badges to the readme.

### CODE REVIEW

**Review by asgibson — APPROVED** [review]
Nice!

**Review by asgibson — CHANGES_REQUESTED** [review]
image
Please add the code report section so that it may be viewed in the results.

**Review by asgibson — CHANGES_REQUESTED** [review]
Missing branch coverage and including test files in report.

putting `--branch --source=onair` into the pytest run should fix that (or `--source=src,data_handling,utils` if the current branch has not yet been rebased to main).

**Comment by jlucas9** [comment]
Closing in favor of https://github.com/nasa/OnAIR/pull/21

**Pull request closed without merging**
